export declare const HIGH_SURROGATE_START = 55296;
export declare const HIGH_SURROGATE_END = 56319;
export declare const LOW_SURROGATE_START = 56320;
export declare const REGIONAL_INDICATOR_START = 127462;
export declare const REGIONAL_INDICATOR_END = 127487;
export declare const FITZPATRICK_MODIFIER_START = 127995;
export declare const FITZPATRICK_MODIFIER_END = 127999;
export declare const VARIATION_MODIFIER_START = 65024;
export declare const VARIATION_MODIFIER_END = 65039;
export declare const DIACRITICAL_MARKS_START = 8400;
export declare const DIACRITICAL_MARKS_END = 8447;
export declare const ZWJ = 8205;
export declare const GRAPHEMS: number[];
export declare function runes(string: any): any[];
export declare function nextUnits(i: any, string: any): 1 | 4 | 2;
export declare function isFirstOfSurrogatePair(string: any): boolean;
export declare function isRegionalIndicator(string: any): boolean;
export declare function isFitzpatrickModifier(string: any): boolean;
export declare function isVariationSelector(string: any): boolean;
export declare function isDiacriticalMark(string: any): boolean;
export declare function isGraphem(string: any): boolean;
export declare function isZeroWidthJoiner(string: any): boolean;
export declare function codePointFromSurrogatePair(pair: any): number;
export declare function betweenInclusive(value: any, lower: any, upper: any): boolean;
export declare function substring(string: any, start: any, width: any): any;
export default runes;
export declare const substr: typeof substring;
