/**
 * do not edit this file
 * source file at test/scripts/src
 */
export declare const reVariationSelectors: RegExp;
export declare const reVariationSelectorsSupplement: RegExp;
export declare const reVariationSelectorsAll: RegExp;
export declare const reZeroWidth: RegExp;
export declare const reZeroWidth2: RegExp;
export declare const reZeroWidthAllSafe: RegExp;
export declare const reZeroWidthAll: RegExp;
export declare const reNBSP: RegExp;
export declare const reNewLine: RegExp;
export declare const reRegExpSpaceWithoutNewLine: RegExp;
export declare const reRegExpSpaceWithoutNewLinePlus: RegExp;
export declare const reRegExpSpace: RegExp;
export declare const reRegExpSpacePlus: RegExp;
export declare const reZeroWidthWithSpaceWithoutNewLine: RegExp;
export declare const reZeroWidthWithSpace: RegExp;
export declare const reZeroWidthTrimWithoutNewLine: RegExp;
export declare const reZeroWidthTrim: RegExp;
export declare const reBomStrict: RegExp;
export declare const reBomUnsafe: RegExp;
